"""update purchases table

Revision ID: 832b8de8f50d
Revises: 0c4b1498d0e6
Create Date: 2025-03-12 11:11:26.612167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832b8de8f50d'
down_revision: Union[str, None] = '0c4b1498d0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.Enum('VALIDATION', 'APPROVED', name='purchasestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###
